# ── python/analysis/gradcam.py ──
"""
Grad-CAM Explainability for Robot Decisions (twc-core wrapper)
==============================================================
Delegates to twc_core.gradcam.GradCAM.
Adds robot-specific explanation report generation.
"""

import numpy as np
from typing import Optional
from twc_core.gradcam import GradCAM as _GradCAM

__all__ = ["GradCAM", "generate_robot_explanation"]


class GradCAM(_GradCAM):
    """Embodied-FL GradCAM — delegates to twc_core.gradcam.GradCAM."""
    pass


def generate_robot_explanation(
    heatmap: np.ndarray,
    action: str,
    confidence: float,
    scene_description: Optional[dict] = None,
) -> str:
    """Generate human-readable explanation for robot action."""
    h, w = heatmap.shape
    center_focus = heatmap[h//4:3*h//4, w//4:3*w//4].mean()
    edge_focus = (heatmap.mean() - center_focus * 0.25) / 0.75

    lines = [
        f"## Robot Action Explanation",
        f"",
        f"**Action**: {action}",
        f"**Confidence**: {confidence:.1%}",
        f"",
        f"### Visual Attention",
    ]

    if center_focus > edge_focus:
        lines.append(f"- Model focused on **central region** (primary object)")
    else:
        lines.append(f"- Model focused on **peripheral region** (context/safety)")

    if scene_description:
        lines.append(f"")
        lines.append(f"### Scene Context")
        for key, val in scene_description.items():
            lines.append(f"- {key}: {val}")

    lines.append(f"")
    lines.append(f"*Generated by Embodied-FL Grad-CAM explainability module.*")
    return "\n".join(lines)
